apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-fitness-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aceest-fitness
      version: blue
  template:
    metadata:
      labels:
        app: aceest-fitness
        version: blue
    spec:
      containers:
        - name: aceest-fitness
          image: 2024tm93009/aceest-fitness:v1.0
          ports:
            - containerPort: 5000
