apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-fitness-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aceest-fitness
      version: green
  template:
    metadata:
      labels:
        app: aceest-fitness
        version: green
    spec:
      containers:
        - name: aceest-fitness
          image: 2024tm93009/aceest-fitness:latest
          ports:
            - containerPort: 5000
