apiVersion: v1
kind: Service
metadata:
  name: aceest-fitness-service
spec:
  type: NodePort
  selector:
    app: aceest-fitness
    version: blue
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080
